baseURL: https://matusnovak.github.io/doxydown/hugo-learn
languageCode: en-us
title: Doxydown Example
theme: hugo-theme-learn
pygmentsUseClasses: false
pygmentsCodeFences: true
pygmentsCodefencesGuessSyntax: true
pygmentsStyle: "tango"
