version: '{build}'

branches:
  except:
    - gh-pages

environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    COMPILER: msvc
    MINGW_DIR_BIN: ''
    TOOLSET: vc15
    ARCH: win32
    GENERATOR: '"Visual Studio 15 2017"'
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    COMPILER: msvc
    MINGW_DIR_BIN: ''
    TOOLSET: vc15
    ARCH: win64
    GENERATOR: '"Visual Studio 15 2017 Win64"'

install:
  - cmd: git submodule update --init
  - cmd: mkdir build
  - cmd: choco install doxygen.install -y
  - cmd: cd build & cmake -G %GENERATOR% -DBUILD_SHARED_LIBS=OFF -DBUILD_TESTING=OFF -DBUILD_TESTS=OFF -DDOXYBOOK_STATIC_STDLIB=ON -DDOXYBOOK_TESTS=ON -DCMAKE_INSTALL_PREFIX="..\install" -DCMAKE_BUILD_TYPE=MinSizeRel .. || exit 1 & cd ..

build_script:
  - cmd: cd build & cmake --build . --target INSTALL --config "MinSizeRel" || exit 1 & cd ..

test_script:
  - cmd: cd example & "C:\Program Files\doxygen\bin\doxygen.exe" || exit 1 & cd ..
  - cmd: cd build & ctest --verbose -C "MinSizeRel" || exit 1 & cd ..

before_deploy:
  - cmd: if defined APPVEYOR_REPO_TAG_NAME 7z.exe a "doxybook2-windows-%ARCH%-%APPVEYOR_REPO_TAG_NAME%.zip" .\install\* || exit 1
  - ps: appveyor SetVariable -Name APPVEYOR_REPO_COMMIT_MESSAGE -Value (git log -1 --pretty=%B)

deploy:
  tag: $(appveyor_repo_tag_name)
  release: '$(appveyor_repo_tag_name)'
  description: '$(APPVEYOR_REPO_COMMIT_MESSAGE)'
  provider: GitHub
  artifact: /.*\.zip/
  draft: false
  prerelease: false
  auth_token:
    secure: v0O1cgji7Mq0HR1/JXfNHuq6UfShlRHB30VIcE2rECanDDm9OzdzMCe9s7L48Ofv
  on:
    APPVEYOR_REPO_TAG: true
