version: 2

jobs:
  build:
    docker:
      - image: gcc:latest
    steps:
      - checkout
      - run:
          name: Dependencies
          command: |
            apt-get update
            apt-get install cmake doxygen -y

      - run:
          name: Submodules
          command: |
            git submodule update --init

      - run:
          name: Compile
          command: |
            mkdir build
            cd build
            cmake -G "Unix Makefiles" -DDOXYDOWN_TESTS=ON -DCMAKE_BUILD_TYPE=MinSizeRel ..
            cmake --build .

      - run:
          name: Generate Doxygen files
          command: |
            cd example
            doxygen

      - run:
          name: Tests
          command: |
            cd build
            ctest -vvv

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
