site_name: Doxydown Example
theme:
  name: 'material'
markdown_extensions:
  - admonition
nav:
  - Home: /doxydown/mkdocs-bootstrap/
  - Classes: /doxydown/mkdocs-bootstrap/Classes
  - Namespaces: /doxydown/mkdocs-bootstrap/Namespaces
  - Modules: /doxydown/mkdocs-bootstrap/Modules
  - Files: /doxydown/mkdocs-bootstrap/Files
  - Related Pages: /doxydown/mkdocs-bootstrap/Pages
